language: python

python:

 - 3.6.1

cache: pip


install:
  - pip install coveralls
  - pip install coverage
  - pip install flask


script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls
