language: 
- python

cache:
- pip

python:
- "3.5"

install:
- pip install coverage
- pip install coveralls

script:
- nosetests tests/test_shoppinglist.py

after_success:
- coverage report
- coveralls
